import { UserProps } from "@app/(authenticated)/users/schema/user.schema";

export const mockUsersData: UserProps[] = [
  {
    email: "user+1@user.com",
    name: "User 1",
    password: "1234",
    roles: ["user"],
    _id: "1",
    createdAt: new Date().toISOString(),
  },
  {
    email: "user+2@user.com",
    name: "User 2",
    password: "1234",
    roles: ["user"],
    _id: "2",
    createdAt: new Date().toISOString(),
  },
  {
    email: "user+3@user.com",
    name: "User 3",
    password: "1234",
    roles: ["user"],
    _id: "3",
    createdAt: new Date().toISOString(),
  },
  {
    email: "user+4@user.com",
    name: "User 4",
    password: "1234",
    roles: ["user"],
    _id: "4",
    createdAt: new Date().toISOString(),
  },
  {
    email: "user+5@user.com",
    name: "User 5",
    password: "1234",
    roles: ["user"],
    _id: "5",
    createdAt: new Date().toISOString(),
  },
  {
    email: "user+6@user.com",
    name: "User 6",
    password: "1234",
    roles: ["user"],
    _id: "6",
    createdAt: new Date().toISOString(),
  },
  {
    email: "user+7@user.com",
    name: "User 7",
    password: "1234",
    roles: ["user"],
    _id: "7",
    createdAt: new Date().toISOString(),
  },
  {
    email: "user+8@user.com",
    name: "User 8",
    password: "1234",
    roles: ["user"],
    _id: "8",
    createdAt: new Date().toISOString(),
  },
  {
    email: "user+9@user.com",
    name: "User 9",
    password: "1234",
    roles: ["user"],
    _id: "9",
    createdAt: new Date().toISOString(),
  },
  {
    email: "user+10@user.com",
    name: "User 10",
    password: "1234",
    roles: ["user"],
    _id: "10",
    createdAt: new Date().toISOString(),
  },
  {
    email: "user+11@user.com",
    name: "User 11",
    password: "1234",
    roles: ["user"],
    _id: "11",
    createdAt: new Date().toISOString(),
  }
];
